name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_hatchbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
